sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - npm install -g grunt-cli
notifications:
  slack:
    secure: lgJj/SealCb3hZsMvclA9VQGwx9TJrtK6ccOZiiHZpJa5in0UkRwE6ymrZ5wqwUagAVwOLYVKHdmrtPMPsaOqavnzq9ItJFqSRo8T5ZgKK+m+X9l88ROn7+QfJyPUkpblhSXMm6+s7duBjdM/no80lA4GEoNWD5G5uQwjJWQSWk=
